image: archlinux
packages:
  - rustup
sources:
  - hg+https://hg.sr.ht/~kirikaza/postgread
tasks:
  - build: |
      cd postgread/
      cargo build --verbose
  - test: |
      cd postgread/
      cargo test --verbose
