image: archlinux
packages:
  - rustup
sources:
  - hg+https://hg.sr.ht/~kirikaza/postgread
tasks:
  - setup: |
      rustup toolchain install nightly
      cd postgread/
      rustup run nightly cargo fetch
      rustup default nightly
  - build: |
      cd postgread/
      cargo build --verbose
  - test: |
      cd postgread/
      cargo test --verbose
