# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
image: rust:1.27

pipelines:
  default:
    - step:
        caches:
          - cargo
        script: # Modify the commands below to build your repository.
          - cargo build -v
          - cargo test -v

definitions:
  caches:
    cargo: ~/.cargo
