name: verify

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.57.0
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Pull postgres image
      run: docker pull postgres:12-alpine
    - name: Pull test-client image
      run: docker pull postgread/test-client:2
    - name: Create an SSH priv/pub key pair
      run: ssh-keygen -t rsa -f test_ssh_key -N ''
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --test tests -- --nocapture
      env:
        POSTGREAD_TEST_CLIENT_SSH_PRIV_KEY_PATH: test_ssh_key
        POSTGREAD_TEST_PG_SERVER_PASSWD: secret
        POSTGREAD_TEST_REUSE_CONTAINERS: 1
    - name: Install clippy
      run: rustup component add clippy
    - name: Check with clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
